from __future__ import annotations

from typing import Any


ALLOWED_ACTIONS = {"open", "close", "hold", "skip", "disable_trading"}
REQUIRED_DECISION_FIELDS = {"action", "decision_reason"}


def validate_decision_payload(
    payload: dict[str, Any],
    *,
    candidate_ids: set[str] | None = None,
) -> list[str]:
    errors: list[str] = []

    missing = sorted(REQUIRED_DECISION_FIELDS - payload.keys())
    if missing:
        errors.append(f"Missing required fields: {', '.join(missing)}")

    action = payload.get("action")
    if action not in ALLOWED_ACTIONS:
        errors.append(f"Unsupported action: {action!r}")

    candidate_id = payload.get("candidate_id")
    if action == "open":
        if not candidate_id:
            errors.append("Open decision requires candidate_id")
        elif candidate_ids is not None and candidate_id not in candidate_ids:
            errors.append(f"Candidate was not generated by code: {candidate_id}")

    return errors

